fix the problem of sigmoid gradient generating NaN
tracel-ai/burn pull request #1140
Opened 2024-01-13 10:48 UTC by wcshds

## Pull Request Template

### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

fix #1139 

### Changes

Use sigmoid's derivative formula directly to avoid differentiating `log` and `exp` in autodiff.

2024-01-13 15:11 UTC, nathanielsimard requested changes

2024-01-13 15:11 UTC, nathanielsimard commented on burn-tensor/src/tensor/ops/tensor.rs
> +    }
We can add this function in `burn-tensor/src/tensor/ops/activation.rs` instead.

2024-01-13 15:11 UTC, nathanielsimard commented on burn-tensor/src/tensor/activation/base.rs
> +    }
I don't think we need full precision here, as it is now declared as a method in the backend. The backend implementations can choose to use full precision regardless of the circumstances. Perhaps we can consider incorporating full precision into the default implementation.

2024-01-15 15:00 UTC, nathanielsimard commented on burn-tensor/src/tensor/ops/activation.rs
> +        B::from_full_precision(tensor_tmp)
Not sure @louisfd if there is a more numerically stable implementation possible here.

2024-01-16 20:02 UTC, louisfd requested changes
Hi, can you check my comment about the naming of the argument to backward, afterwards it will be ready

2024-01-16 20:16 UTC, wcshds commented on burn-tensor/src/tensor/ops/activation.rs
> +        x: FloatTensor<B, D>,
Done.

2024-01-16 21:19 UTC, louisfd approved these changes
Thanks a lot

2024-01-16 21:20 UTC, merged