Add tests: Slice assign vs Cat in LSTM backward
tracel-ai/burn pull request #1146
Opened 2024-01-17 21:07 UTC by louisfd

In order to fix #1098, where it is mentioned that LSTM backward does not work in its current state but would if slice_assign were replaced by cat in its computations, I wrote some tests: one for slice_assign backward, and one specifically for LSTM backward, both comparing the result to the one we get with cat. 
For both tests it worked fine, making me unsure if there is really a bug with slice_assign.

2024-01-18 02:51 UTC, wcshds commented
I don't know if this is relevant to the problem. If use `let fake_loss = hidden_state;` instead of `let fake_loss = cell_state + hidden_state;`, the lstm which uses `slice_assign` will panic.

2024-01-18 03:17 UTC, wcshds commented
I think slice_assign does have some bugs. If you change the return value of the current lstm implementation to `(batched_cell_state.clone()), batched_hidden_state + batched_cell_state.clone() - batched_cell_state.clone ())`, the parameters of lstm can be updated.

2024-01-18 18:53 UTC, nathanielsimard commented
> I don't know if this is relevant to the problem. If use `let fake_loss = hidden_state;` instead of `let fake_loss = cell_state + hidden_state;`, the lstm which uses `slice_assign` will panic.

I think this is expected, since you only track gradients for tensors that require them or are connected to some. If you only use the hidden state, then maybe there is no connection to the actual parameters of the model.

2024-01-18 18:56 UTC, nathanielsimard requested changes
See my comments bellow

2024-01-18 18:56 UTC, nathanielsimard commented on burn-core/src/nn/rnn/lstm.rs
> +    fn test_batched_backward_pass() {
I think we should cleanup that test, like a pretty standard backward pass test, without having to use the cat function. Just checking if the gradients are calculated can be enough here.

2024-01-18 19:20 UTC, wcshds commented
> > I don't know if this is relevant to the problem. If use `let fake_loss = hidden_state;` instead of `let fake_loss = cell_state + hidden_state;`, the lstm which uses `slice_assign` will panic.
> 
> I think this is expected, since you only track gradients for tensors that require them or are connected to some. If you only use the hidden state, then maybe there is no connection to the actual parameters of the model.

But the final output in lstm is a tensor that contains the hidden state of each time step, which is exactly what I need, and also the output of pytorch. Cell state only plays a role in the lstm calculation process.

2024-01-25 14:36 UTC, louisfd commented
@nathanielsimard twice already I thought I had pushed my change but I just realized this PR is from my personal branch 😢 now it's there

2024-01-25 15:02 UTC, nathanielsimard approved these changes

2024-01-25 15:03 UTC, nathanielsimard commented
@louisfd I think you need to merge main and run clippy & fmt.

2024-01-29 02:29 UTC, merged