Docs/guide
tracel-ai/burn pull request #1183
Opened 2024-01-26 11:21 UTC by ashdtu

### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

#1103 : Better documentation of Guide example.
#1153: Improve Tensor introduction
#1154: Improve Dataset transform guide

### Changes
Corresponding to each issue, here are the changes in this PR:
#1103 : The changes suggested bridge the gap between the example code provided in examples/guide vs what is written in guide. The documentation currently lacked the partitioning of code into model, data, training files similar to the example code. This sometimes made it hard to follow if for eg someone is copy-pasting code from there. Fixed these issues and added helpful comments with reference to original example.

#1153
* Added introduction of  Tensor with rank, similarity/diff for people coming from PyTorch.
* Initialization from data, floats api. .convert() , elem etc.
*  Underline importance of ownership and cloning with example.
* No stateful operations : **TODO** (discuss)

#1154 
* Added introduction of dataset transform with example usages.
* Batcher omitted as already present in current guide in mnist tutorial and other concepts covered by Rust introduction commit.

2024-01-26 15:36 UTC, nathanielsimard requested changes
Some small corrections, see my comments bellow.

2024-01-26 15:36 UTC, nathanielsimard commented on burn-book/src/building-blocks/dataset.md
> +let PartialData = PartialDataset<ShuffledDataset<DbPedia, DbPediaItem>>;
Prefer using `type` for type alias

```rust
type PartialData = PartialDataset<ShuffledDataset<DbPedia, DbPediaItem>>;
```

2024-01-26 15:36 UTC, nathanielsimard commented on burn-book/src/building-blocks/dataset.md
> +of each transform can be found at the [API reference](https://burn.dev/docs/burn/data/dataset/transform/index.html).
I would add a sentence or two specifying that the dataset transformation are lazy by default except when specified otherwise.

2024-01-26 15:36 UTC, nathanielsimard commented on burn-book/src/building-blocks/tensor.md
> +characterized by the number of dimensions D in its declaration. The actual shape of the tensor is inferred from
I don't think PyTorch is characterized by the size of its each dimension. There is nothing specified for the element type, the shape, or the rank. All of those are runtime properties. In contrast, in Burn, we have those specified as types!

2024-01-26 15:36 UTC, nathanielsimard commented on burn-book/src/building-blocks/tensor.md
> +The `Data` struct has two fields: value & shape. To access the data of any tensor, we use the method `.to_data()`.
`to_data()` if we want to reuse the tensor afterward, or `into_data()` otherwise.

2024-01-26 15:36 UTC, nathanielsimard commented on burn-book/src/building-blocks/tensor.md
> +Burn Tensors are primarily initialized using the `from_data()` method which takes the `Data` struct as input.
Also add the fact that `Data` can be built from `slices`, `vectors`, etc. See https://github.com/tracel-ai/burn/blob/main/burn-tensor/src/tensor/data.rs

2024-01-26 15:36 UTC, nathanielsimard commented on burn-book/src/building-blocks/tensor.md
> +let tensor_2 = Tensor::<Backend, 1>::from_floats([1.0, 2.0, 3.0]);
The different with from `floats` is that the element type is f32, where from data the element type is defined by the backend. When the backend is generic, you have to use some sort of convertion.

2024-01-26 15:36 UTC, nathanielsimard commented on burn-book/src/building-blocks/tensor.md
> +`let tensor_4 = Tensor::<B, 1, Int>::from_data(Data::from([(item.age as i64).elem()])`.
Specify that using `elem` is only possible when the trait `ElementConversion` is imported.

2024-01-26 15:36 UTC, nathanielsimard commented on burn-book/src/building-blocks/tensor.md
> +which is very convenient for reusing tensor buffers and improving performance. For that reason, we don't provide
for reusing tensor buffers or even fusing operations into a single kernel (link to burn fusion maybe).

2024-01-26 17:42 UTC, louisfd commented on burn-book/src/building-blocks/tensor.md
> +    // If we want to utlize them as well for further operations, they will need to be cloned in similar fashion.
There's a typo in utilize, i prefer `use` to utilize in general

2024-01-26 18:43 UTC, antimora commented
Quick feedback re formatting (haven't read the content in details yet). 

I recommend you format the text using something like prettier if you have a VS/Neovim plug-in. We have a configuration for prettier: https://github.com/tracel-ai/burn/blob/main/burn-book/.prettierrc.json (or you can define yours)

This helps formatting tables and wrapping markdown text.

2024-01-29 19:43 UTC, ashdtu commented
Many thanks @nathanielsimard, @louisfd, and @antimora for the suggestions. Incorporated in the latest commit. Let me know if it's good to go.

2024-01-30 13:56 UTC, nathanielsimard approved these changes

2024-01-30 15:24 UTC, ashdtu commented
Thank again for the review. Made the minor fixes suggested. Merging now!

2024-01-30 15:25 UTC, merged