Add setup instructions for burn-tch
tracel-ai/burn pull request #1185
Opened 2024-01-26 20:46 UTC by laggui

### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

Closes #587

### Changes

This draft PR adds detailed instructions to setup the `tch` backend with LibTorch and a simple example to test that the installation is successful.

Because many different installation configurations are possible, I'd love to get some feedback on the recommended method.

At this time I switched to a manual installation with proper documentation since the automatic download doesn't work for all use cases (e.g., MPS).

Maybe we still want to offer automatic by default and add separate that as a feature to allow manual installation support?

2024-01-26 20:47 UTC, laggui commented
@nathanielsimard @antimora would love to get your opinion

2024-01-26 21:15 UTC, laggui commented
Just chatted with Nathaniel, the suggestion is:

1. Keep automatic download by default
2. Set the correct tch environment variables based on feature flags (cpu (default), cu118 and cu121 for current libtorch version)
  - Still undecided if this is the best practice or other approaches would be better
4. Provide manual instructions for other use cases (as currently added in the documentation)

2024-01-27 21:01 UTC, antimora requested changes
Thank you for working on this. It's a great start and I am sure, we will extend it as we encounter issues. 

Can you also add Troubleshooting section. Often people report ATen errors which is related to incorrectly installing CUDA version. You might be able to fine this from https://github.com/tracel-ai/burn/issues/587 comments. 

As I recommend we keep auto downloader, which also works for Mac. The manual configuration is a recommended path.

2024-01-29 13:00 UTC, laggui commented on burn-tch/Cargo.toml
> +tch = { version = "0.14.0" }
Yes agreed. We agreed to keep automatic installation as a default, was going to make the changes today.

2024-01-29 13:03 UTC, laggui commented on burn-tch/README.md
> +[Burn mnist example](https://github.com/tracel-ai/burn/tree/main/examples/mnist).
Ahhh yes that makes sense! Will do.

2024-01-29 17:19 UTC, laggui commented
> Thank you for working on this. It's a great start and I am sure, we will extend it as we encounter issues.
> 
> Can you also add Troubleshooting section. Often people report ATen errors which is related to incorrectly installing CUDA version. You might be able to fine this from #587 comments.
> 
> As I recommend we keep auto downloader, which also works for Mac. The manual configuration is a recommended path.

We're back to automatic download now! :) And a flag `burn-tch/custom-libtorch` can be specified for a manual/custom libtorch installation.

Sadly, there is no way to "automatically" set the `TORCH_CUDA_VERSION` environment variable for the `tch` dependency.. `[env]` is only for the cargo config and the dependencies are built before so there's no way to "hack" this in a `build.rs`. Would have been nice to avoid this for our users, but instead I've added instructions for the automatic download w/ CUDA (which basically only requires setting the `TORCH_CUDA_VERSION` beforehand).

Regarding the troubleshooting section, I'm not sure what should be included. The CUDA driver version compatibility is already mentioned is the instructions and no CUDA toolkit is actually required (contrary to what some issues seem to refer to). For a manual installation direct download links are provided along with instructions to set the proper environment variables that would otherwise cause issues. Do you mean adding troubleshooting for even more custom installations (i.e., using a local LibTorch version that is not the currently listed version supported by `tch`)?

2024-01-29 18:52 UTC, laggui commented on burn-core/Cargo.toml
> +tch-custom = ["burn-tch?/custom-libtorch"]
Oh right! The worst part is I stumbled upon that last Friday but it completely slept my mind today 🤦 

Thanks 🙏  will fix

2024-01-30 21:02 UTC, louisfd approved these changes
Looks good to me on a superficial level, haven't delved into all the details. There's only one typo

2024-01-30 21:19 UTC, laggui commented on burn-tch/README.md
> +To install `tch-rs` with a different LibTorch distribution, you will have to set the to manually
Whoops, good catch!

Leftover from a previous commit where the wording was different. Removed "to set the".

2024-01-31 15:18 UTC, merged