Rename GELU to Gelu
tracel-ai/burn pull request #1311
Opened 2024-02-14 18:08 UTC by antimora

This is to follow Rust naming convention

## Pull Request Template

### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Changes

1. Rename GELU to Gelu in code
2. Change in docs

### Testing

Ran all checks

2024-02-14 21:50 UTC, louisfd requested changes
I agree there is inconsistency, for instance we have `Lstm` and `Gru` instead of LSTM and GRU, but we also have `ReLU`, `MSELoss`, ... I think if we want to make that move we should rename them too.

2024-02-14 21:50 UTC, louisfd commented on README.md
> +As an example, you could write your own Gelu activation function with the high level tensor api (see
I would certainly not change it here because it's not the Rust struct but the deep learning concept

2024-02-15 15:23 UTC, nathanielsimard approved these changes

2024-02-15 16:20 UTC, antimora commented
@louisfd, it's a good suggestion. I will rename others in a new PR.

2024-02-15 16:21 UTC, louisfd approved these changes
Perfect!

2024-02-15 16:39 UTC, merged