Feat/swiglu
tracel-ai/burn pull request #1507
Opened 2024-03-22 15:03 UTC by ashdtu

## Pull Request Template

### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

#1504 

### Changes

Implement [SwiGLU activation](https://paperswithcode.com/method/swiglu) module to be used in LLM models

2024-03-22 16:47 UTC, antimora requested changes
It looks but tests are missing for some reason.

2024-03-25 11:07 UTC, louisfd approved these changes
LGTM. One small comment but approved in advance

2024-03-25 11:07 UTC, louisfd commented on crates/burn-core/src/nn/swiglu.rs
> +pub struct SwiGLUConfig {
Should be camel case, see #1316

2024-03-25 17:15 UTC, ashdtu commented on crates/burn-core/src/nn/swiglu.rs
> +pub struct SwiGLUConfig {
Done! thanks

2024-03-25 17:16 UTC, ashdtu commented
@antimora Added tests. Let me know if it looks good to merge.

2024-03-25 19:41 UTC, antimora approved these changes
LGTM

2024-03-25 19:55 UTC, merged