Add f16 support in the wgpu backend
tracel-ai/burn pull request #1582
Opened 2024-04-07 12:09 UTC by p1-0tr

## Pull Request Template

### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

Split from: https://github.com/tracel-ai/burn/pull/1475

### Changes

The burn-wgpu backend currently does not support computations on 16 bit floats. This. for example, limits the ability to run LLMs on top of Burn, on widely available hardware. So, add 16 bit float support in burn-wgpu.

### Testing

I used this change on top of my changes which add the ability to run with Dawn instead of wgpu, to run llama2-burn with f16.

2024-04-11 13:17 UTC, nathanielsimard requested changes

2024-04-11 13:17 UTC, nathanielsimard commented on crates/burn-jit/src/codegen/dialect/gpu/shader.rs
> +    Half,
There is no need to add `Half` here, `Float` should cover all float types of all precisions in this context.

2024-04-11 13:17 UTC, nathanielsimard commented on crates/burn-jit/src/element.rs
> +    }
The gpu element would be `Float` here.

2024-04-11 13:17 UTC, nathanielsimard commented on crates/burn-wgpu/src/compiler/wgsl/compiler.rs
> +        };
I would check using `F::wgpu_elem() == Elem::F16` instead.

2024-04-11 13:17 UTC, nathanielsimard commented on crates/burn-wgpu/src/compiler/wgsl/compiler.rs
> +            gpu::Elem::Half => F::wgpu_elem(),
This line pretty much explains why we don't need `Half` in the `gpu::Elem` enum :)

2024-09-13 17:22 UTC, laggui commented
This belongs in cubecl now 🙂 will close here due to the big changes we made with the migration.

2024-09-13 17:22 UTC, closed without merging