PReLu ONNX import
tracel-ai/burn pull request #1721
Opened 2024-05-03 15:39 UTC by Arjun31415

## Pull Request Template

### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs
#1714 

### Changes

Added PReLu ONNX -> burn operator

### Testing

Not tested yet.

2024-05-03 15:45 UTC, Arjun31415 commented
The rust code produced - 
````rs
// Generated from ONNX "./onnx-tests/tests/prelu/prelu.onnx" by burn-import
use burn::nn::prelu::PRelu;
use burn::nn::prelu::PReluConfig;
use burn::nn::PRelu;
use burn::record::FullPrecisionSettings;
use burn::record::Recorder;
use burn::{
    module::Module,
    tensor::{backend::Backend, Tensor},
};


#[derive(Module, Debug)]
pub struct Model<B: Backend> {
    prelu1: PRelu<B>,
    phantom: core::marker::PhantomData<B>,
    device: burn::module::Ignored<B::Device>,
}


impl<B: Backend> Default for Model<B> {
    fn default() -> Self {
        Self::from_file("./out/prelu", &Default::default())
    }
}

impl<B: Backend> Model<B> {
    pub fn from_file(file: &str, device: &B::Device) -> Self {
        let record = burn::record::PrettyJsonFileRecorder::<FullPrecisionSettings>::new()
            .load(file.into(), device)
            .expect("Record file to exist.");
        Self::new(device).load_record(record)
    }
}

impl<B: Backend> Model<B> {
    #[allow(unused_variables)]
    pub fn new(device: &B::Device) -> Self {
        let prelu1 = PReluConfig::new(0, 0.009999999776482582).init(device);
        Self {
            prelu1,
            phantom: core::marker::PhantomData,
            device: burn::module::Ignored(device.clone()),
        }
    }

    #[allow(clippy::let_and_return, clippy::approx_constant)]
    pub fn forward(&self, input1: Tensor<B, 2>) -> Tensor<B, 0> {
        let prelu1_out1 = self.prelu1.forward(input1);
        prelu1_out1
    }
}
```
I think the `PReluConfig` initialization is wrong . 
```rs
        let prelu1 = PReluConfig::new(0, 0.009999999776482582).init(device);
```
the number of parameters should not be 0 and initial alpha should be 0.01 exactly and not this approximate value

2024-05-03 15:57 UTC, antimora requested changes
Great start but we are missing two types of unit tests (under onnx-tests and in crates/burn-import/src/burn/node/prelu.rs). Also Prelu ONNX spec does not have alpha and numb_parameters, so there is no need to extract configuration.

2024-05-03 15:57 UTC, antimora commented on crates/burn-import/src/burn/node/prelu.rs
> +        imports.register("burn::nn::prelu::PRelu");
PRelu seems to be imported twice here.

2024-05-03 15:57 UTC, antimora commented on crates/burn-import/src/onnx/op_configuration.rs
> +    }
ONNX Spec does not have alpha nor num_parameters, so they should be removed: https://onnx.ai/onnx/operators/onnx__PRelu.html

I recommend you would remove prelu_config function and just use PReluConfig::new() with it's defaults. You do not need to store or pass it.

config is meant to extract attributes (such as [Conv attributes](https://onnx.ai/onnx/operators/onnx__Conv.html#attributes))  as Module configuration.

You can also see the ONNX example you checked in does not contain alpha and num_params:

<img width="911" alt="image" src="https://github.com/tracel-ai/burn/assets/939125/7e1ffe29-3563-498e-90b2-bfc5bde80965">

2024-05-03 15:57 UTC, antimora commented on crates/burn-import/src/onnx/to_burn.rs
> +        let config = prelu_config(&node);
I would remove this too per my above comment.

2024-05-03 15:59 UTC, antimora commented
FYI, to run ONNX test:

```shell
[burn-import]% cd onnx-tests
[onnx-tests]% cargo test
```

to run code gen tests:
```sh
[burn-import]% cargo test
```

2024-05-03 16:09 UTC, Arjun31415 commented
I also get this warning 
```log
DEBUG burn_import::onnx::from_onnx: Number of initializers: 1    
DEBUG burn_import::onnx::from_onnx: Number of outputs: 1    
DEBUG burn_import::onnx::proto_conversion: Converting ONNX node with type "PRelu"    
DEBUG burn_import::onnx::from_onnx: renaming node "/relu1/PRelu"    
 WARN burn_import::onnx::dim_inference: Must implement dimension inference for PRelu    
DEBUG burn_import::onnx::from_onnx: checking inputs for node "prelu1"    
DEBUG burn_import::onnx::from_onnx: 
```

2024-05-03 16:28 UTC, antimora commented
> I also get this warning
> 
> ```
> DEBUG burn_import::onnx::from_onnx: Number of initializers: 1    
> DEBUG burn_import::onnx::from_onnx: Number of outputs: 1    
> DEBUG burn_import::onnx::proto_conversion: Converting ONNX node with type "PRelu"    
> DEBUG burn_import::onnx::from_onnx: renaming node "/relu1/PRelu"    
>  WARN burn_import::onnx::dim_inference: Must implement dimension inference for PRelu    
> DEBUG burn_import::onnx::from_onnx: checking inputs for node "prelu1"    
> DEBUG burn_import::onnx::from_onnx: 
> ```

Yeah, you will need to add dim inference in dim_inference.rs file. You can use same as input function since the output will have the same dimensions.

2024-05-03 16:30 UTC, antimora commented
Also please update the supported https://github.com/tracel-ai/burn/blob/main/crates/burn-import/SUPPORTED-ONNX-OPS.md as well

2024-05-03 16:37 UTC, Arjun31415 commented
Ok so I think what is pending is the `dim_inference` and loading the `weight` from the onnx into `alpha` of the Burn `PreluConfig`. I need help with this, where exactly do I do the latter part

2024-05-03 16:38 UTC, Arjun31415 commented
if I do those two then tests would also be fixed

2024-05-04 12:45 UTC, Arjun31415 commented
Ok I think dim inference is also fixed. Now I just need to load the prelu weight into burn

2024-05-04 15:43 UTC, Arjun31415 commented
Ok I think it is done

2024-05-04 18:45 UTC, antimora approved these changes
Looks great!

Thank you for your contribution to the Burn project!

2024-05-04 18:45 UTC, merged