added maxpool1d onnx operator
tracel-ai/burn pull request #1725
Opened 2024-05-05 13:33 UTC by Arjun31415

## Pull Request Template

### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

#1714 

### Changes

_Summarize the problem being addressed and your solution._

### Testing

_Describe how these changes have been tested._

2024-05-05 20:24 UTC, antimora requested changes
Thank you for your help adding ONNX ops. Overall, it looks perfect with minor required changes. One unit test is failing and I commented on it. Here is the failed test:

<img width="732" alt="image" src="https://github.com/tracel-ai/burn/assets/939125/090ce1ca-cce2-40e9-8a57-6d3419bae940">

2024-05-05 20:24 UTC, antimora commented on crates/burn-import/src/burn/node/max_pool1d.rs
> +                        .with_strides(1)
`.with_strides(1)` should bd `.with_stride(1)` 

Currently the test is failing.

2024-05-05 20:24 UTC, antimora commented on flake.lock
This file should be removed. 

You are welcome to add `flake.lock` into `.gitignore` so it does not get accidentally committed.

2024-05-05 20:24 UTC, antimora commented on flake.nix
Same as above.

2024-05-06 03:11 UTC, Arjun31415 commented on flake.lock
Apologies, I did not mean to commit it

2024-05-06 05:35 UTC, Arjun31415 commented
@antimora fixed. The flake being commited was an issue on my end ( I am using nixos and need to specify the dependencies required to build the project for reproducibility ).

2024-05-06 15:50 UTC, antimora approved these changes
LGTM

Thank you for your contribution!

2024-05-06 15:51 UTC, merged