Add documentation to burn core nn
tracel-ai/burn pull request #1746
Opened 2024-05-07 21:18 UTC by jwric

## Pull Request Template

### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ x ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

Related to #594

### Changes

Revised rust documentation for burn core neural network modules.

2024-05-09 13:07 UTC, laggui requested changes
Thanks for the major clean-up 🧹 🙏 

Some minor comments to address, mainly about the form to be consistent in the changes.

2024-05-09 13:07 UTC, laggui commented on crates/burn-core/src/nn/transformer/pwff.rs
> +/// FFN(x) = max(0, xW1 + b1)W2 + b2
Keep the math in ticks?

`FFN(x) = max(0, xW1 + b1)W2 + b2`

2024-06-13 14:01 UTC, jwric commented on crates/burn-core/src/nn/norm/batch.rs
> +/// - `Y` is the output tensor
I saw we grouped them for the other formulas, I don't know why this one was different lol

2024-06-13 14:02 UTC, jwric commented on crates/burn-core/src/nn/leaky_relu.rs
>  }
👌 👌

2024-06-13 14:03 UTC, jwric commented on crates/burn-core/src/nn/norm/layer.rs
> +/// - `β` is the learnable bias#[derive(Module, Debug)]
yes :}

2024-06-13 14:04 UTC, jwric commented on crates/burn-core/src/nn/pool/max_pool2d.rs
> +/// Configuration to create an [2D max pooling](MaxPool2d) layer using the [init function](MaxPool2dConfig::init).
😅

2024-06-13 14:11 UTC, jwric commented on crates/burn-core/src/nn/norm/instance.rs
> +/// Should be created using the [InstanceNormConfig](InstanceNormConfig) struct.
Oh alr. I thought it was clearer that it was a technical reference to the code struct, it can be removed

2024-06-13 14:13 UTC, jwric commented on crates/burn-core/src/nn/norm/instance.rs
> +/// Should be created using the [InstanceNormConfig](InstanceNormConfig) struct.
we did this in some other places, i could change them too

2024-06-13 15:01 UTC, jwric commented on crates/burn-core/src/nn/norm/instance.rs
> +        }.forward(input)
Something like the commit [f514031](https://github.com/tracel-ai/burn/pull/1746/commits/f51403197ac406137ab5ff2a428b57bb17c4dc22)?

2024-06-13 16:02 UTC, laggui commented on crates/burn-core/src/nn/norm/instance.rs
> +        }.forward(input)
Perfect 🔥

2024-06-13 16:12 UTC, laggui approved these changes
LGTM 🚀

2024-06-13 16:50 UTC, merged