define generics in doc comment for type Wgpu
tracel-ai/burn pull request #1804
Opened 2024-05-23 20:08 UTC by bionicles

I didn't know what these meant, others will likely face a similar question, this can save some others some hunting around and make  it more intuitive to work with wgpu

## Pull Request Template

### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

_Provide links to relevant issues and dependent PRs._

### Changes

_Summarize the problem being addressed and your solution._

### Testing

_Describe how these changes have been tested._

2024-05-24 00:29 UTC, nathanielsimard requested changes
The documentation is duplicated for now when fusion is enabled, could you also add those comments on top declaration when fusion isn't enabled?

Thanks

2024-05-29 11:06 UTC, bionicles commented
hmm, i'm not sure what you mean by fusion, could you please post a picture of what you're talking about so i can try to reproduce that? @nathanielsimard

2024-05-31 21:12 UTC, nathanielsimard commented
![image](https://github.com/tracel-ai/burn/assets/14095719/297c3002-8199-454d-9bda-3181b99ce749)
@bionicles 

The are two different `pub type Wgpu` with different feature flags.

2024-06-15 18:13 UTC, bionicles commented
@nathanielsimard hey, i'm sorry that brief fix took so long, I was working on other things and this fell to the 2nd page of github notifications. GitHub Workspaces enabled me to go to the patch i made before and fix what you wanted, so please let me know if that's good, just a minor doc comments improvement and your feedback was on point

2024-07-16 15:42 UTC, nathanielsimard commented
The generic arguments are gone, so the comments would not be very useful 😅

2024-07-16 15:42 UTC, closed without merging

2024-07-18 19:11 UTC, bionicles commented
no problemo, thanks for informing me