feat: added range onnx import
tracel-ai/burn pull request #1834
Opened 2024-05-28 21:33 UTC by JachymPutta

### Checklist

- [X] Confirmed that `run-checks all` script has been executed.
- [X] Made sure the book is up to date with changes in this PR.

### Changes

Add the range import to onnx

### Testing

`cargo test range`

2024-05-30 11:58 UTC, laggui requested changes
Good job! 🙂 

I have one minor request over form when checking the types, otherwise looks good to me.

2024-05-30 11:58 UTC, laggui commented on crates/burn-import/src/burn/node/range.rs
> +        };
If the three fields are all supposed to be scalar, I suggest we change the node fields to:

```rust
pub struct RangeNode {
    pub start: ScalarType,
    pub end: ScalarType,
    pub step: ScalarType,
    pub output: TensorType,
}
```

and the logic to check the extract the scalar types can go in the `range_conversion`.

2024-05-30 13:00 UTC, laggui commented on crates/burn-import/src/burn/node/range.rs
> +        };
Well yes, scalars are simply represented as 0-dim tensors. Basically what I am suggesting is just to move the type handling outside of the forward node method to the `range_conversion` function instead, a bit like this:

```rust
  fn range_conversion(node: Node) -> RangeNode {
      let output = node.outputs.first().unwrap().to_tensor_type();
      let start = node.inputs.first().unwrap().to_type();
      let end = node.inputs.get(1).unwrap().to_type();
      let step = node.inputs.get(2).unwrap().to_type();

      // Check/convert start, end & step to ScalarType just as it was done in the forward method
     // ...

      RangeNode::new(start, end, step, output)
  }
```

2024-05-30 13:56 UTC, laggui approved these changes
LGTM! 🚀

2024-05-31 21:40 UTC, antimora approved these changes
LGTM


Thank you for your contribution!

2024-05-31 21:40 UTC, merged