Feat: Add `movedim` tensor operator
tracel-ai/burn pull request #1876
Opened 2024-06-10 19:23 UTC by LilDojd

## Pull Request Template

### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

None

### Changes

Added `movedim` default implementation. Mirrors the [PyTorch one](https://pytorch.org/docs/stable/generated/torch.movedim.html).

This just wraps a call to permute with sanity checks, but moving one/few axes while keeping all others inbound is a common enough operation to warrant its specific convenient syntactic sugar.

### Testing

Added unit tests.

2024-06-10 20:23 UTC, LilDojd commented on crates/burn-tensor/src/tensor/api/base.rs
> +    pub fn movedim<S: MovedimArgs>(self, src: S, dst: S) -> Tensor<B, D, K> {
I've just realised the signature should be more general:

```diff
-    pub fn movedim<S: MovedimArgs>(self, src: S, dst: S) -> Tensor<B, D, K> {
+    pub fn movedim<S1: MovedimArgs, S2: MovedimArgs>(self, src: S1, dst: S2) -> Tensor<B, D, K> {
```

2024-06-13 13:46 UTC, nathanielsimard requested changes
Thanks for the contribution!

2024-06-13 13:46 UTC, nathanielsimard commented on crates/burn-tensor/src/tensor/api/base.rs
> +        let rank = self.dims().len();
I think just `D` would work.

2024-06-13 13:46 UTC, nathanielsimard commented on crates/burn-tensor/src/tensor/api/check.rs
> +        let duplicates = dims.iter().find(|&&x| !uniq.insert(x));
I think we should avoid creating hashmap or hashset when possible, especially when working with sequences < 10 in size, just doing for loops would probably be the best here.

2024-06-13 13:46 UTC, nathanielsimard commented on crates/burn-tensor/src/tensor/api/base.rs
> +        let mut m = HashMap::new();
I would avoid using an hashmap here. maybe a BTreeMap would be lighter.

2024-06-14 10:33 UTC, LilDojd commented on crates/burn-tensor/src/tensor/api/base.rs
> +        let rank = self.dims().len();
Right, my bad

2024-06-14 10:34 UTC, LilDojd commented
Thanks for the review! I have addressed your comments in recent commit

2024-06-14 13:01 UTC, nathanielsimard approved these changes

2024-06-14 13:01 UTC, merged