[WIP] Add deform_conv2d as implemented in torchvision
tracel-ai/burn pull request #2147
Opened 2024-08-09 14:47 UTC by wingertge

## Add Deformable Convolution Layers v1/v2

Help would be welcome, I've been looking at the kernel so long I can no longer see my mistakes. Getting a few more pairs of eyes on it would be helpful.

### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

A lot of resnet variants currently replace most conv2d layers with deform_conv2d. See [torchvision docs](https://pytorch.org/vision/main/generated/torchvision.ops.deform_conv2d.html)

### Changes

Adds the relatively popular deform_conv2d layer initially implemented in torchvision in 2021.
The backwards pass is not yet implemented in `burn-ndarray`, need to make sure the code is correct before porting it to `ndarray`.

### Testing

* Forward pass is tested with comparison to pytorch output (weight groups currently failing, trying to investigate)
* Backward pass yet to be tested

2024-08-11 08:43 UTC, wingertge commented
Currently blocked on atomics being added to `cubecl`

2024-09-16 21:55 UTC, wingertge commented
Finally done and ready to review

2024-09-23 14:50 UTC, louisfd requested changes
Just a few questions, otherwise very nice!

2024-09-23 18:00 UTC, wingertge commented on crates/burn-jit/src/kernel/conv/deform_conv2d.rs
> +pub(crate) fn bilinear_interpolate<F: Float>(
I don't believe there is a cube function that does bilinear interpolate for a single element? All I could find was the kernel that does it for a whole tensor.

2024-09-23 18:02 UTC, wingertge commented on crates/burn-jit/src/kernel/conv/deform_conv_transpose2d.rs
> +        return;
I did forget about that.

2024-09-23 18:48 UTC, louisfd commented on crates/burn-jit/src/kernel/conv/deform_conv2d.rs
> +pub(crate) fn bilinear_interpolate<F: Float>(
Good, only wanted to check if you had realized something similar existed

2024-09-23 18:49 UTC, louisfd approved these changes
LGTM

2024-09-23 19:17 UTC, merged