enable doc_auto_cfg to show feature-req-hint in docs.rs
tracel-ai/burn pull request #2271
Opened 2024-09-11 09:29 UTC by kingwingfly

## Pull Request Template

### Checklist

- [ ] Confirmed that `run-checks all` script has been executed.
- [ ] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

None

### Changes

According to [this](https://github.com/rust-lang/rust/issues/43781), `cargo doc` has an cool feature `doc_auto_cfg`, which helps show the features-required hints like `tokio`.

```rust
# in lib.rs
#![cfg_attr(docsrs, feature(doc_auto_cfg))]
```

```toml
# in Cargo.toml
[package.metadata.docs.rs]
features = ["doc"]
rustdoc-args = ["--cfg", "docsrs"]
```

Apart from that, I also add `documentation` keys in `[package]`.

### Testing

```sh
RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --features doc --no-deps -p burn --open
```

I just checked that it works and show things like:

<img width="1335" alt="Screenshot 2024-09-11 at 17 24 06" src="https://github.com/user-attachments/assets/e06998f9-2940-4ea1-8061-cf0e792655ee">

But I don't know how to automize this with xtask, and it needs nightly Rust as the version used by docs.rs.

2024-09-16 12:36 UTC, nathanielsimard requested changes
Somehow it doesn't work for everything:

![image](https://github.com/user-attachments/assets/df60a027-c058-43ad-beec-da4b73e4ec5a)

I would have expected the backend modules to show which feature flag is necessary, do you have an idea why it doesn't appear to work for those?

2024-09-16 16:12 UTC, kingwingfly commented
Oh, it seems not so simple. However, it works well for `burn-core` and `burn-train`:

<img width="1335" alt="Screenshot 2024-09-17 at 00 11 01" src="https://github.com/user-attachments/assets/f5a0f014-7a25-4699-876b-a15a8bdc4ad6">

But  it fails when coming to `burn`.

It's so buggy, and I may spend more time in finding the fixing method.

2024-09-17 05:56 UTC, kingwingfly commented
@nathanielsimard 

I found a way to fix this, and now it works for `burn` package. However, it is just to re-export all things in `burn_core` and `burn_train` instead of easily `pub use burn_core::*`, now it looks quite tedious.

2024-09-18 14:18 UTC, laggui commented
> @nathanielsimard
> 
> I found a way to fix this, and now it works for `burn` package. However, it is just to re-export all things in `burn_core` and `burn_train` instead of easily `pub use burn_core::*`, now it looks quite tedious.
> 
> I have compared the new doc page and the old, and I think nothing lost. I hope I didn't forget exporting something.

That seems a little error prone 😅 would be nice if there was a way to do this properly without re-exporting

2024-09-18 16:49 UTC, kingwingfly commented
> That seems a little error prone 😅 would be nice if there was a way to do this properly without re-exporting

I hope so. I found current less graceful solution by a minimal example. I'll try asking for help from the feature developper and the community.

2024-09-18 17:55 UTC, kingwingfly commented
I just found this is allowed:
```rust
use crate_a::*; // instead of `use crate_a::{B, C, D, ...}

#[cfg(feature = "a")]
use crate_a::A;
```

Now it will be less possible to make a mistake. 

By the way, as the features are given in the `Cargo.toml`, it is reasonable to use it in the package somewhere explicitly maybe... 

The features are written in `Cargo.toml` only for generating feature page, and user can still enable them with `--features tch,train`. So, using it in `lib.rs` can at least make them more meaningful. 

And I found there are also many problems about features in this repo. For example, my editor told me `tch` and `train` features are enabled even they are not included in `default` feature. And they are actually enabled by `example/text-generation`. This can be prevented by [required-features](https://doc.rust-lang.org/cargo/reference/cargo-targets.html#the-required-features-field), and it's also tedious to fix ( here's an example: 1. [set required features](https://github.com/kingwingfly/encrypt-config/blob/dev/tests/Cargo.toml) and 2. [set --features for each example](https://github.com/kingwingfly/encrypt-config/blob/dev/.github/scripts/test.sh) )... I'll make another issue as I become available.

2024-09-24 13:49 UTC, nathanielsimard commented
@kingwingfly When building an example from the root workspace directory, all dependencies listed in the workspace are built, not one the ones specified in the example. I though this was a cargo workspace thing, is there a way to remove that behavior?

2024-09-24 14:42 UTC, kingwingfly commented
@nathanielsimard 

#2289

Using required-feature can solve this problem. But it then needs to modify test and example shell scripts to enable features needed.

2024-09-26 12:19 UTC, nathanielsimard commented on crates/burn/src/lib.rs
> +        };
I don't like the fact we need to know when adding a new metrics, that it should be manually re-exported in the burn root crate. Only for the feature flag to show on the docs :/

2024-10-09 13:14 UTC, nathanielsimard approved these changes

2024-10-09 13:15 UTC, merged