feature(tensor): Add chunk op
Tracel-AI/burn pull request #998
Opened 2023-11-24 20:53 UTC by dcvz

## Pull Request Template

### Checklist

- [x] Confirmed that `run-checks all` script has been executed.
- [x] Made sure the book is up to date with changes in this PR.

### Related Issues/PRs

Solves #970 (at least at a base implementation). I believe @Kelvinyu1117 might be working on a backend optimized version. I needed to implement this for my project, so thought I'd PR it.

### Changes

Adds a base tensor implementation for chunking.

### Testing

Tests have been made for the different cases for chunk.

2023-11-25 02:48 UTC, Kelvinyu1117 commented
yup, probably I can do it on top of this PR.
I'm still looking at how can we fall back to our own implementation if the backend doesn't implement.

2023-11-27 14:36 UTC, nathanielsimard requested changes

2023-11-27 14:36 UTC, nathanielsimard commented on burn-tensor/src/tests/ops/chunk.rs
> +    fn test_chunk_not_divisible() {
You are missing the `#[test]` attribute.

2023-11-27 14:58 UTC, nathanielsimard approved these changes

2023-11-27 14:58 UTC, merged